### 1. 회원가입 성공 테스트 (정상적인 데이터)
POST http://localhost:8080/api/members
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "password1234",
  "nickname": "개발왕"
}

### 2. 회원가입 실패 테스트 (이메일 형식 X, 비밀번호 짧음)
POST http://localhost:8080/api/members
Content-Type: application/json

{
  "email": "이건이메일이아니야",
  "password": "123",
  "nickname": "김"
}

### 3. 로그인 성공 테스트 (DB에 있는 진짜 아이디/비번)
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "password1234"
}

### 4. 로그인 실패 테스트 (비밀번호 틀림)
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "wrongPassword"
}

### 5. 로그아웃 테스트 (세션 삭제)
POST http://localhost:8080/api/logout


### 2. 글쓰기 요청 (로그인 상태 유지됨)
POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "2026년 첫 게시글",
  "content": "JPA와 세션 정복 완료! 이제 나는 백엔드 개발자다."
}

### 3. 게시글 조회 (작성자 확인)
GET http://localhost:8080/api/posts/1

### 글쓰기 (반복해서 3~4번 실행)
POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "test1",
  "content": "test1"
}

### 글쓰기 (반복해서 3~4번 실행)
POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "test2",
  "content": "test2"
}

### 글쓰기 (반복해서 3~4번 실행)
POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "test3",
  "content": "test3"
}

### 4. (V1) 게시글 전체 조회 (N+1 문제 발생시키기)
GET http://localhost:8080/api/v1/posts

### 4. (V2) 게시글 전체 조회 (N+1 문제 발생시키기)
GET http://localhost:8080/api/v2/posts